pipeline:
  NODEJSCI16:
    name: Node16 CI
    image: node:16-alpine3.13

    command: 
      - apk add --no-cache autoconf automake file g++ gcc libc-dev libtool make nasm pkgconfig python3 zlib-dev vips-dev vips
      - NODE_ENV=production yarn install
      - NODE_ENV=production yarn build
      #- cp test/test.yml .config
      #- yarn test
