include: 
  - local: '/.gitlab/renovate.gitlab-ci.yml'
  - local: '/.gitlab/workflows/nodejs.gitlab-ci.yml'

variables:
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
  RENOVATE_EXTRA_FLAGS: '--autodiscover=true --autodiscover-filter=blackcrystal/ayuskey'

renovate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
