nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs

# ref: https://github.com/yarnpkg/berry/blob/ac2668904bdcd804e531291c749b9d17b8d3acd7/packages/yarnpkg-core/sources/StreamReport.ts#L40
progressBarStyle: "hogsfather"

packageExtensions:
# v11では現状不要
#  "chartjs-adapter-date-fns@*":
#    peerDependencies:
#      "date-fns": "*"
  "@bull-board/api@*":
    peerDependencies:
      "@bull-board/ui": "*"
  "koa-views@*":
    dependencies:
      "pug": "*"
  "consolidate@*":
    dependencies:
      "ejs": "*"
