docker:
  image: nikolaik/python-nodejs:python3.11-nodejs18-alpine
  stage: build
  before_script:
    - apk add --no-cache build-base
    - node devtools/diag-environment.js
    - pip install loyalcat
  script:
    - loyalcat -a ci -c ${CI_COMMIT_SHA} -p 0827fb59-d7c3-46b6-874e-b6e77943843a
