image: node:18.12.0-alpine3.16

variables:
  POSTGRES_DB: test-misskey
  POSTGRES_HOST_AUTH_METHOD: trust

services:
  - name: postgres:15.0-alpine
    alias: postgres
  - name: redis:7.0-alpine
    alias: redis

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir .pnpm-store
  - node devtools/diag-environment.js
  - apk add --no-cache ffmpeg
  - cp test/test.yml .config

test:
  script:
    - pnpm i
    - pnpm build
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
