image: node:18.12.0-alpine3.16

variables:
  POSTGRES_DB: test-misskey
  POSTGRES_HOST_AUTH_METHOD: trust

services:
  - name: postgres:15.0-alpine
    alias: postgres
  - name: redis:7.0-alpine
    alias: redis

before_script:
  - node devtools/diag-environment.js
  - pnpm i
  - apk add --no-cache ffmpeg
  - cp test/test.yml .config

test:
  script:
    - pnpm build
    - pnpm test
