image: node:18.12.0-alpine3.16

variables:
  POSTGRES_DB: test-misskey
  POSTGRES_PASSWORD: '1234'
#  POSTGRES_HOST_AUTH_METHOD: trust

default:
  services:
    - name: postgres:15.0-alpine
      alias: db
    - name: redis:7.0-alpine

before_script:
#  - echo https://mirrors.cat.net/alpine/v3.16/main > /etc/apk/repositories
#  - echo https://mirrors.cat.net/alpine/v3.16/community >> /etc/apk/repositoriess
  - apk add --no-cache ffmpeg curl 
  - apk add --no-cache autoconf automake file g++ gcc libc-dev libtool make nasm pkgconfig python3 zlib-dev git
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir .pnpm-store
  - node devtools/diag-environment.js
  - cp .gitlab/test.yml .config

test:
  script:
    - pnpm i
    - pnpm build
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
